services:
  postgres:
    image: pgvector/pgvector:pg17
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${ENV_POSTGRES_USER}
      POSTGRES_PASSWORD: ${ENV_POSTGRES_PASSW}
      POSTGRES_DB: ${ENV_DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    #      - ./docker-config/database/init.sql:/docker-entrypoint-initdb.d/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${ENV_POSTGRES_USER} -d ${ENV_DATABASE_NAME}" ]
      interval: 10s
      timeout: 10s
      retries: 3

  backend:
    build: .
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${ENV_DATABASE_NAME}
      SPRING_DATASOURCE_USERNAME: ${ENV_POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${ENV_POSTGRES_PASSW}
    depends_on:
      postgres:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: ./src
        - action: rebuild
          path: ./pom.xml

  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    restart: unless-stopped
    ports:
      - "8978:8978"
    volumes:
      - cloudbeaver_workspace:/opt/cloudbeaver/workspace
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
  cloudbeaver_workspace:
